apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: praxis-ingress
  namespace: praxis
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: praxis.minilab
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: praxis-api
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: praxis-frontend
                port:
                  number: 80
